### ISSUE TITLE
MultiFarming

### ISSUE THREAD

**Issue by hokiepokedad** [amintalkin/MyBot-AIO#15]

**Comment by PRASHANT8421** [comment]
plz aad

**Comment by amintalkin** [comment]
It will be added soon

**Comment by PRASHANT8421** [comment]
thanks again

**Comment by PRASHANT8421** [comment]
I love your boots

**Comment by dondale8** [comment]
Before releasing Multi-Farming
- Please increase delay + add more check For Every action at multi-farm Function ? Coz some time it takes time to move to next step and stuck. Idk if that from my internet or google server.

1- Starting at Press on connect/disconnect

2- Wait for Account page To load

3- Chose Account

4- Wait for load msg to load

5- Press load

**Comment by amintalkin** [comment]
dondale8: Ok I will Inform to Icecube about this

**Comment by amintalkin** [comment]
Done Added In v2.1.2
